#pragma once

typedef struct tagInfo {
	float fX, fY;
	float fCX, fCY;
}INFO;

enum STATE {STATE_TITLE, STATE_LOBBY, STATE_STAGE_SELECT, STATE_INGAME, STATE_LEVELUP_CARD, STATE_GAMEOVER,STATE_CLEAR, STATE_PAUSE, STATE_END};